class GameData:
    # Actions Lists
    north=["north","n","go north", "walk north", "run north", "up"]
    south=["south","s","go south", "walk south", "run south", "down"]
    east=["east","e","go east", "walk east", "run east", "right"]
    west=["west","w","go west", "walk west", "run west", "left"]
    look=["look","look around", "see", "search", "find", "observe"]
    sleep=["sleep", "go to sleep", "doze off", "zzz"]
    score=["score", "show score", "what is my score", "what's my score", "tell me my score"]
    yes=["yes", "okay", "ok", "sure", "yeah",  "yep", "ye", "yh", "yea", "ya", "y", "yup", "uhuh", "mhm", "mhmm", "mmm", "mm", "m", "yeh", "alright", "k", "all right", "of course", "duh", "why not"]
    rock=["pick up rock", "pick up shimmering rock", "pick up shiny rock"]
    mine=["mine rock", "mine ores", "mine rocks", "mine ore", "mine emerald", "mine", "use pickaxe", "mine with pickaxe", "mine ores with pickaxe", "mine ore with pickaxe"]
    put_rock=["put rock in hole", "put rock in wall", "place rock in wall", "place rock in hole", "put rock", "place rock", "insert rock", "put the rock in the hole"]
    put_sword=["put sword in hole", "put sword in wall", "place sword in wall", "place sword in hole", "put sword", "place sword", "insert sword", "put the sword in the hole"]
    pick_up_sword=["pick up sword", "collect sword", "get sword", "retrieve sword", "pick up the sword"]
    drop_sword=["put down sword", "put sword down", "drop sword", "lose sword"]
    swing_sword=["attack", "swing sword", "use sword", "attack with sword", "swing", "swing the sword"]
    open_chest=["open chest", "look in chest", "open the chest", "unlock chest", "unlock the chest"]
    zap=["attack", "attack ghost", "zap", "zap ghost", "stun ghost"]
    carpet=["look under carpet", "search under carpet", "carpet", "search carpet", "move carpet", "inspect carpet", "look under the carpet"]
    leave=["leave", "exit", "i want to leave", "get me out of here", "i hate this place", "let me leave", "let me exit"]
    throw=["throw orb", "throw", "chuck", "throw the orb", "throw it"]
